=== kosgdk/Sp/src/test/resources/dbunit/datasets/dtd/test_sp_database_allFieldsOptional.dtd
<!ELEMENT dataset (
    clients*|
    order_position*|
    orders*|
    products*|
    properties*|
    sp*)*>

<!ELEMENT clients EMPTY>
<!ATTLIST clients
    id CDATA #IMPLIED
    name CDATA #IMPLIED
    real_name CDATA #IMPLIED
    phone CDATA #IMPLIED
    note CDATA #IMPLIED
    referrer CDATA #IMPLIED
>

<!ELEMENT order_position EMPTY>
<!ATTLIST order_position
    id CDATA #IMPLIED
    order_id CDATA #IMPLIED
    product_id CDATA #IMPLIED
    price_ordered CDATA #IMPLIED
    price_sp CDATA #IMPLIED
    price_vendor CDATA #IMPLIED
    quantity CDATA #IMPLIED
    note CDATA #IMPLIED
>

<!ELEMENT orders EMPTY>
<!ATTLIST orders
    id CDATA #IMPLIED
    client CDATA #IMPLIED
    sp CDATA #IMPLIED
    weight CDATA #IMPLIED
    status CDATA #IMPLIED
    prepaid CDATA #IMPLIED
    note CDATA #IMPLIED
    date_ordered CDATA #IMPLIED
    date_completed CDATA #IMPLIED
    delivery_price CDATA #IMPLIED
    place CDATA #IMPLIED
>

<!ELEMENT products EMPTY>
<!ATTLIST products
    id CDATA #IMPLIED
    name CDATA #IMPLIED
    price CDATA #IMPLIED
    link CDATA #IMPLIED
    photo CDATA #IMPLIED
    vkid CDATA #IMPLIED
    imagelink CDATA #IMPLIED
    deleted CDATA #IMPLIED
    vkphotoid CDATA #IMPLIED
    weight CDATA #IMPLIED
>

<!ELEMENT properties EMPTY>
<!ATTLIST properties
    id CDATA #IMPLIED
    percent_sp CDATA #IMPLIED
    percent_discount CDATA #IMPLIED
    percent_bank_commission CDATA #IMPLIED
>

<!ELEMENT sp EMPTY>
<!ATTLIST sp
    id CDATA #IMPLIED
    number CDATA #IMPLIED
    percent CDATA #IMPLIED
    status CDATA #IMPLIED
    date_start CDATA #IMPLIED
    date_end CDATA #IMPLIED
    date_to_pay CDATA #IMPLIED
    date_sent CDATA #IMPLIED
    date_to_receive CDATA #IMPLIED
    date_received CDATA #IMPLIED
    date_to_distribute CDATA #IMPLIED
>

=== kosgdk/Sp/src/test/resources/unitils/dataset/OrderPositionDbIntegrationTest/delete_ShouldNotCascadeDeleteChild.xml
<!DOCTYPE dataset SYSTEM "dtd\test_sp_database_allFieldsOptional.dtd">
    <dataset>
        <clients id="1"/>
        <clients id="2"/>
        <sp id="1"/>
        <sp id="2"/>

        <orders id="1" client="1" sp="1"/>
        <orders id="2" client="2" sp="2"/>
        <products id="1"/>
        <products id="2"/>

        <order_position id="2" order_id="2" product_id="2"/>
    </dataset>
